// frontend/schedulerpro-react/src/App.tsx
import { useRef } from 'react';
import { BryntumSchedulerPro } from '@bryntum/schedulerpro-react';
import { schedulerProConfig } from './schedulerproConfig';

function App() {
    const schedulerPro = useRef(null);

    return (
        <BryntumSchedulerPro ref={schedulerPro} {...schedulerProConfig} />
    );
}

export default App;

// frontend/schedulerpro-vue/src/App.vue
<script setup lang="ts">
import { BryntumSchedulerPro } from '@bryntum/schedulerpro-vue-3';
import { schedulerProConfig } from './schedulerproConfig.ts';
</script>

<template>
    <bryntum-scheduler-pro
        v-bind="schedulerProConfig"
    />
</template>

<style lang="scss">
@import './assets/main.css';
</style>
